name: AI Korrekturleser

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  proofread:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        # Wir müssen den gesamten Verlauf holen, um die geänderten Dateien zu finden
        with:
          fetch-depth: 0

      - name: Geänderte Markdown-Dateien finden
        id: changed_files
        run: |
          # Finde alle .md-Dateien, die in dieser Pull Request geändert wurden
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.md$')
          echo "changed_files=${FILES}" >> $GITHUB_OUTPUT

      - name: Python einrichten
        if: steps.changed_files.outputs.changed_files != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Python-Abhängigkeiten installieren
        if: steps.changed_files.outputs.changed_files != ''
        run: pip install requests

      - name: Korrekturlese-Skript ausführen
        id: proofread
        if: steps.changed_files.outputs.changed_files != ''
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.changed_files }}
        run: python scripts/proofread.py

      - name: Korrektur als Kommentar posten
        if: success() && steps.proofread.outputs.corrected_text != ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Korrekturvorschlag für deine geänderten Dateien ✨\n\n---\n\n${{ steps.proofread.outputs.corrected_text }}`
            });
