- name: Korrekturlese-Skript ausführen
        id: proofread
        run: |
          PR_BODY=$(echo "${{ github.event.pull_request.body }}" | sed 's/"/\\"/g' | sed "s/'/\\'/g")
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g' | sed "s/'/\\'/g")
          
          # Führe den API-Aufruf aus und speichere die Antwort
          RESPONSE=$(curl -s -H 'Content-Type: application/json' \
            -d "{\"contents\":[{\"parts\":[{\"text\": \"Bitte korrigiere den folgenden Newsletter-Entwurf auf Grammatik, Rechtschreibung und Stil. Gib nur den korrigierten Text zurück, ohne eine Einleitung. Originaltitel: ${PR_TITLE}. Originaltext: ${PR_BODY}\"}]}]}" \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.GOOGLE_AI_API_KEY }}")
            
          # Gib die komplette Antwort von der API zur Fehlersuche aus
          echo "API Response:"
          echo "${RESPONSE}"
          
          # Versuche, den Text zu extrahieren
          CORRECTED_TEXT=$(echo "${RESPONSE}" | python3 -c "import sys, json; data = json.load(sys.stdin); print(data.get('candidates', [{}])[0].get('content', {}).get('parts', [{}])[0].get('text', 'Fehler: Konnte keine Korrektur in der API-Antwort finden.'))")
          
          echo "corrected_text<<EOF" >> $GITHUB_OUTPUT
          echo "$CORRECTED_TEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
