name: AI Korrekturleser

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  proofread:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Python-Abhängigkeiten installieren
        run: pip install requests

      - name: Korrekturlese-Skript ausführen
        id: proofread
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: python scripts/proofread.py

      - name: Korrektur als Kommentar posten
        if: success() && steps.proofread.outputs.corrected_text != ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Korrekturvorschlag von deiner KI ✨\n\n---\n\n${{ steps.proofread.outputs.corrected_text }}`
            });
