name: Berechtigungs-Test

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  test-kommentar:
    runs-on: ubuntu-latest
    steps:
      - name: Test-Kommentar posten
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello World! Der Berechtigungs-Test war erfolgreich.'
            })
